site_name: CarAV Wiki
site_url: https://turb0yoda.github.io/
nav:
    - Home: index.md
    - Buying Guide: buying.md
    - Setting Gains: gains.md
    - Sound Deadener Showdown Archive: SDS.md
theme:
  name: material